#!/bin/bash

source ../config/sdrplay-250k

if [ "$1" ]; then freq=$1; fi
echo Frequency = $freq
filename="./data/"`date +"soapy_%Y%m%d_%H%M%S"`"_"`printf "%.0f" $freq`"_"$samplerate"_fc.raw"

mkdir -p ./data

../bin/sdr $device "$antenna" "$gains" $freq $samplerate 10 > $filename
