#!/bin/bash

source ../config/sdrplay-250k

if [ "$1" ]; then freq=$1; fi
echo Frequency = $freq
filename="./data/spectrum_"`date +"%Y-%m-%d_%H-%M-%S"`"_"`printf "%.0f" $freq`"_"$samplerate""

mkdir -p ./data

../bin/sdr $device "$antenna" "$gains" $freq $samplerate 10 \
    | ../bin/spectrum 8192 1024 10.0 $filename
