#!/bin/bash

if [ -z "$1" ]; then freq=`cat ./config/freq`; else freq=$1; fi
echo Frequency = $freq
freqM=`python -c "print($freq/1e6)"`

airspyhf_rx -f $freqM -a `cat ./config/samplerate` -r stdout \
    | ./bin/filter 8 \
    | ./bin/decimate 8 \
    | ./bin/filter 8 \
    | ./bin/agc \
    | ffmpeg -f f32le -ac 2 -ar $( echo $((`cat ./config/samplerate` / 8)) ) -i - \
        -filter:a "volume=60dB" -f ogg -ac 1 -ar 12000 -content_type audio/ogg icecast://source:hackme@localhost:4625/sdr
