#!/bin/bash

if [ -z "$1" ]; then freq=`cat ./config/freq`; else freq=$1; fi
echo LSB carrier Frequency = $freq
freqM=`python -c "print(($freq-1500)/1e6)"`
echo Airspy tune Frequency = $freqM MHz

r=`cat ./config/samplerate`
r_out=`python -c "print($r/16)"`

airspyhf_rx -f $freqM -a $r -r stdout \
    | ./bin/filter 8 \
    | ./bin/decimate 8 \
    | ./bin/filter 8 \
    | ./bin/decimate 2 \
    | ./bin/demod lsb 4 \
    | ./bin/filter 2 \
    | ./bin/agc \
    | ffmpeg -loglevel quiet -f f32le -ac 2 -ar $r_out -i - \
        -filter:a "volume=50dB" -f ogg -ac 1 -ar 6000 -content_type audio/ogg icecast://source:hackme@localhost:4625/sdr
