#!/bin/bash

if [ -e "src/kissfft/kiss_fft.c" ]
then
    echo Kiss FFT exists
else
    echo Loading Kiss FFT ...
    git clone https://github.com/mborgerding/kissfft ./src/kissfft
fi

mkdir -p bin

for file in ./src/*.c
do
    output=`echo $file | sed "s/\.c//" | sed "s/src/bin/"`
    echo Compiling $file ...
    if [[ $file = "./src/sdr.c" ]]; then
        gcc -std=c99 $file -lSoapySDR -lm -o $output -O3 -Wall -Wextra
    elif [[ $file = "./src/spectrum.c" ]]; then
        gcc -std=c99 $file -lm -o $output -I kissfft ./src/kissfft/kiss_fft.c -O3 -Wall -Wextra
    else
        gcc -std=c99 $file -lm -o $output -O3 -Wall -Wextra
    fi
done

echo Done.
