#!/bin/bash

if [ -z "$1" ]; then freq=`cat ./config/freq`; else freq=$1; fi
echo Frequency = $freq

./bin/sdr `cat ./config/device` `cat ./config/antenna` `cat ./config/gains` $freq `cat ./config/samplerate` 0 \
    | ./bin/filter 8 \
    | ./bin/decimate 8 \
    | ./bin/filter 4 \
    | ./bin/agc \
    | play -v 500 -r $( echo $((`cat ./config/samplerate` / 8)) ) -t raw -b 32 -c 2 -e float -
