#!/bin/bash

r=`cat ./config/samplerate`
r_out=`python -c "print($r/16)"`

while true
do
    nc `cat ./config/remote_ip` `cat ./config/remote_port` \
        | ./bin/filter 4 \
        | ./bin/demod usb 4 \
        | ./bin/filter 2 \
        | ./bin/agc \
        | play -q -v 300 -r $r_out -t raw -b 32 -c 2 -e float -
    sleep 1
done
