#!/bin/bash

# Transmit audio stream into existing IQ stream
# Argument is audio stream URL

mkfifo ./data/iq_output_pipe
mkfifo ./data/P1

ffmpeg -y -i "$1" -f f32le -ac 1 -ar `cat ./config/samplerate` -filter:a "lowpass=f=3500,adelay=15000|15000" ./data/P1 &

sleep 1

nc `cat ./config/remote_ip` `cat ./config/remote_port` \
    | ./bin/tx ./data/P1 -10e3 1e-3 am `cat ./config/samplerate` 1.0 \
    > ./data/iq_output_pipe
