#!/bin/bash

ip=`cat ./config/remote_ip`
port=`cat ./config/remote_port`
r=`cat ./config/samplerate`
r_out=`python -c "print($r/16)"`

while true
do
    echo Listening $ip:$port
    nc $ip $port \
        | ./bin/filter 4 \
        | ./bin/demod usb 4 \
        | ./bin/filter 2 \
        | ./bin/agc \
        | play -q -V0 -v 50 -r $r_out -t raw -b 32 -c 2 -e float -
    sleep 1
done
