#!/bin/bash

source ../../config/sdrplay-250k

samplerate=125000
freq=200e3 # to listen Poland at 225kHz
if [ "$1" ]; then freq=$1; fi
echo Frequency = $freq

../../bin/sdr $device "$antenna" "$gains" $freq $samplerate 0 \
    | ../../bin/fft-filter 16384 3000 3500 0.0001 \
    | netcat -l -p $local_port
