#!/bin/bash

source ../../config/sdrplay-250k

samplerate=125000
freq=225e3 # to listen Poland at 225kHz
if [ "$1" ]; then freq=$1; fi
echo Frequency = $freq

../../bin/sdr $device "$antenna" "$gains" $freq $samplerate 0 \
    | ../../bin/agc \
    | ../../bin/fft-filter 65536 64336 65386 0.0001 \
    | ffmpeg -loglevel quiet -f f32le -ac 2 -ar 125000 -i - \
        -filter:a "volume=30dB" -f ogg -ac 1 -ar 11025 -b 32k -content_type audio/ogg icecast://source:hackme@localhost:4625/sdr

#    | netcat -l -p $local_port # for test
