#!/bin/bash

while true
do
    nc `cat ../config/remote_ip` `cat ../config/remote_port` \
        | ../bin/filter 4 \
        | ../bin/agc \
        | play -q -v 1500 -r $( echo $((`cat ../config/samplerate` / 8)) ) -t raw -b 32 -c 2 -e float -
    sleep 1
done
