#!/bin/bash

source ../config/sdrplay-256k

../bin/sdr $device "$antenna" $gains $freq $samplerate 0 \
    | ../bin/waterfall 2048 500 25.0 4 \
    | ffplay -f rawvideo -pixel_format gray -video_size 2048x500 -i -
