#!/bin/bash

source ../config/sdrplay-250k

if [ "$1" ]; then freq=$1; fi
echo Frequency = $freq

../bin/sdr $device "$antenna" "$gains" $freq $samplerate 0 \
    | ../bin/filter 2 \
    | ../bin/decimate 2 \
    | netcat -l -p $local_port
