#!/bin/bash

source ../../config/sdrplay-250k

if [ "$1" ]; then freq=$1; fi
echo Frequency = $freq

../../bin/sdr $device "$antenna" "$gains" $freq $samplerate 0 \
    | ../../bin/add tick 0.03 25 \
    | ../../bin/add tick 0.1 250 \
    | netcat -l -p $local_port
