#!/bin/bash

source ../../config/remote-by-tcp

nc $remote_ip $remote_port \
    | ../../bin/waterfall 2048 360 50.0 4 \
    | ffplay -framerate 999999 -f rawvideo -pixel_format gray -video_size 2048x360 -i -
